server:
  port: 8080

spring:
  application:
    name: api-gateway


  config:
    import: "optional:file:./application.yml"

  cloud:
    gateway:
      routes:
        - id: user-service
          uri:  http://user-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

jwt:
  secret: ${JWT_SECRET:defaultSecret}