server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**
          filters:
            - StripPrefix=1
            - name: JwtAuthFilter

        - id: reservant-service
          uri: lb://reservant-service
          predicates:
            - Path=/api/reservations/**
          filters:
            - StripPrefix=1
            - name: JwtAuthFilter