server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: hotel-service
          uri: http://hotel-service:8082
          predicates:
            - Path=/api/hotel/**
          filters:
            - JwtAuthFilter
            - StripPrefix=1

        - id: reservation-service
          uri: http://reservation-service:8083
          predicates:
            - Path=/api/reservation/**
          filters:
            - JwtAuthFilter
            - StripPrefix=1

jwt:
  secret: ${JWT_SECRET}